version: "2"
services:
  mysql:
    container_name: mysql
    build: ./.docker/mysql
    command: --max_allowed_packet=10G
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./.docker/dbdata/mysql:/var/lib/mysql
      - ./.docker/dumps:/dumps
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.docker/dbdata/redis:/data
    ports:
      - "6379:6379"
