version: "3"

services:
  mysql:
    container_name: mysql
    build: ./.docker/mysql
    command: --max_allowed_packet=10G
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./.docker/dbdata/mysql:/var/lib/mysql
      - ./.docker/dumps:/dumps
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - ./.docker/dbdata/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  admin:
    build:
      context: ./.docker/rails/
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s /usr/src/entrypoint.sh
    container_name: dialog-admin
    ports:
      - 3000:3000
    volumes:
      - $DIALOG_ADMIN_DIR:/usr/src/app
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
      - "lvh.me:172.17.0.1"
    restart: unless-stopped

  api:
    build:
      context: ./.docker/api/
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s /usr/src/entrypoint.sh
    container_name: dialog-api
    ports:
      - 4000:4000
    volumes:
      - $DIALOG_API_DIR:/usr/src/app
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  pwa:
    build:
      context: ./.docker/pwa/
    entrypoint: /usr/src/entrypoint.sh
    container_name: dialog-pwa
    ports:
      - 5000:5000
    volumes:
      - $DIALOG_PWA_DIR:/usr/src/app
    depends_on:
      - api
    restart: unless-stopped
