version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./.docker/dbdata/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.docker/dbdata/redis:/data
    ports:
      - "6379:6379"
